### PR TITLE
Switch from --privileged to --cap-add DAC_READ_SEARCH --cap-add SYS_A…

### PR DESCRIPTION
**Pull request by fryfrog**
This should close issue #14.

I don't really understand what `DAC_READ_SEARCH` is, but that fixes it. And `SYS_ADMIN` too. Better than running `ALL` or `--privileged`.

### CODE REVIEW

**Comment by fryfrog** [comment]
Could you try this locally? I'm still seeing weird behavior wrt video.ubnt.com. It isn't showing up online there, but I can get to it locally no problem. :/

**Comment by fryfrog** [comment]
And now after a very long delay, it connected... but I happen to be running with --cap-add NET_ADMIN right now... :/

Will re-try w/o it.

**Comment by fryfrog** [comment]
And now it is showing up w/ just the two --cap-add in the diff.

/shrug

**Comment by pducharme** [comment]
So, is this change good? should I merge it?

**Comment by fryfrog** [comment]
Technically, it is just a change to the readme... so it isn't going to hurt anything. Could you give your local docker of it a run w/ those options and confirm they work for you?

**Comment by pducharme** [comment]
How I would do that? I'm running this on Unraid with a WebUI for the Docker.  I do not run any Docker Run command, the GUI deal with that...

**Comment by fryfrog** [comment]
Humm, where does it get the run command from?

**Comment by pducharme** [comment]
Really don't know, it's all hidden in the back :P

**Comment by fryfrog** [comment]
In that case, I don't see how it could be pulling the commands from the readme since that is a fairly recent addition, so I'd say this is safe. Can you get cli to run a command?

**Comment by pducharme** [comment]
This is what is ran when I click "OK" : 

`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name="UniFi-Video" --net="bridge" --privileged="true" -e TZ="America/New_York" -e HOST_OS="unRAID" -p 6666:6666/tcp -p 7080:7080/tcp -p 7443:7443/tcp -p 7445:7445/tcp -p 7446:7446/tcp -p 7447:7447/tcp -v "/mnt/cache/appdata/unifi-video/logs/":"/var/log/unifi-video":rw -v "/mnt/cache/appdata/unifi-video/data/":"/var/lib/unifi-video":rw -v "/mnt/user/camera/":"/videos":rw pducharme/unifi-video-controller
322b3b327549cc3e31bed440baf0b73f097e0734c1bf93741c800b214889162f

The command finished successfully!`

**Comment by fryfrog** [comment]
Ah, it works because `--privileged="true"`, but I don't know how you change that. In theory, you can replace that w/ the two --cap-add arguments and it should work. It'll make your docker "safer" in that it can do less.

Probably nbd either way.

/shrug, merge it.

**Comment by pducharme** [comment]
I probably can't change the "priviledged" because of that :  

http://take.ms/auuFiW

It is part of the GUI.

**Comment by fryfrog** [comment]
To be clear, this is just a change to the readme. Anyone *not* using unraid will use this to start it.

But in unraid, I'm *guessing* if you flip that slider from true -> false, you'll get all the cap-add and cap-drop options and could leave the defaults on, adding the two in this readme.

**Comment by pducharme** [comment]
No, flipping the switch to off only remove the "--priviledged = True" from the run command.  Ill merge now.

**Pull request merged**
