### PR TITLE
Update to 3.9.12.

### PR DESCRIPTION
**Pull request by fryfrog**
Do the ol' 3.9.12 update. Yay.

### CODE REVIEW

**Comment by stefancrain** [comment]
@fryfrog have you been involved in the release workflow in the past? Does a new version usually get tested in `master` before moving to `release`? I'm inclined to merge this into `release` and tag it as `3.9.12`

**Comment by fryfrog** [comment]
I just sent you an email, is there a good way we can chat? :)

**Comment by fryfrog** [comment]
But to answer your question, I generally run it myself for a little bit and then promote it to release and tag it.

**Comment by cwhits** [comment]
@fryfrog or @stefancrain, can you merge this into `release` and tag it as `3.9.12`?

**Pull request merged**
