### PR TITLE
Update to v3.10.13

### PR DESCRIPTION
**Pull request by TBK**
https://community.ui.com/releases/UniFi-Video-3-10-13/7cca7ae9-f4ff-4844-a7c4-b8163bb81f21

### CODE REVIEW

**Comment by TBK** [comment]
FYI I build the new image and updated my own deployment. It has been working flawlessly for the last 7 hours.

3.10.13 is the only version working with the latest camera firmware.

**Comment by SebbeM** [comment]
> 3.10.13 is the only version working with the latest camera firmware.

I'm currently having issues with the live feed from my camera running firmware v4.22.13. Could this be related to the controller running 3.10.12?

**Comment by cwhits** [comment]
@fryfrog @pducharme any chance of getting this merged? 🙏

**Comment by fryfrog** [comment]
Thanks for @mentioning me, merged. Didn't realize they'd done a 3.10.13! I'll push it over to `release` after I run it for a day or so.

**Comment by drpaulatkinson** [comment]
do you think 3.10.13 is stable? are you likely to update the 'latest' tag in docker hub to this yet?

**Comment by fryfrog** [comment]
Done, sorry about forgetting!

**Comment by hartimcwildfly** [comment]
The docker image tag for 3.10.13 is missing. Can somebody fix this?

**Comment by hartimcwildfly** [comment]
Workaround for this:
```
docker pull pducharme/unifi-video-controller:latest
docker tag pducharme/unifi-video-controller:latest pducharme/unifi-video-controller:3.10.13
```

**Comment by fryfrog** [comment]
Tag added. :)

**Pull request merged**
