### PR TITLE
Update to 3.8.0

### PR DESCRIPTION
**Pull request by fryfrog**
Running this locally for the next few days, we'll see how it looks.

### CODE REVIEW

**Comment by fryfrog** [comment]
Actually, I'm not running it yet. I goofed up my local stuff.

**Comment by fryfrog** [comment]
So super important... it needs port 7442 now. I've updated the README, but I'm not sure how to reasonably do this sort of update w/o breaking everything and making people figure it out. :/

**Comment by fryfrog** [comment]
Still happily chugging along, this is ready to go in... probably along with an update of the first post in your forum thread. :/

**Comment by zumbrunnen** [comment]
Shouln't the EXPOSE line in Dockerfile be `EXPOSE 7442 7443 7445 7446 7447 7080 6666` now? I think port 7442 must be added there, too.

**Comment by NathanZepol** [comment]
It looks like that has already been done @zumbrunnen : https://github.com/pducharme/UniFi-Video-Controller/commit/14bde0229252fd04e5a6fdf9bc9c456a1201bcf7

**Pull request merged**
